### ISSUE TITLE
Move or remove `apg` dependency

### ISSUE THREAD

**Issue by fwal** [ldthomas/apg-js2-exp#3]
Hi!

I'm trying to use this package in a react native app but due to the dependency on `apg`, this won't work. However, I don't see that package being used in the code (only `app-lib`).

Could we make the dependency on `apg` a dev dependency, or maybe remove it altogether?

**Comment by fwal** [comment]
Oh I found the dependency now: https://github.com/ldthomas/apg-js2-exp/blob/a51720a371f76685836e4e9d1c93b08229eb1ff7/src/sabnf-generator.js#L11

**Comment by fwal** [comment]
(The root cause is that `apg` is using `fs` which doesn't exist in react native 😞)

**Comment by ldthomas** [comment]
Looks like you have found the answer. Thanks for your interest in apg-exp.
